export const SimulateTyping = ({ children, content }) => {
    CREATE REF DYNAMICALLY HERE,
    AND CALL THE HOOK HERE TO AVOID RE-RENDERS WHICH CAUSE THE REF TO LOSE TRACK BECOMING NULL, UNCOMMENT CODE IN
    LANDING TO SEE ERROR
}